#ifndef __CUSTOM_INI__
#define __CUSTOM_INI__

char customini[] =
"; Custom game settings\n"
"[General]\n"
"version=12\n"
"\n"
"[TWINE]\n"
"Good_Name=007 - The World Is Not Enough (E)(U)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[BIOFREAKS]\n"
"Good_Name=Bio F.R.E.A.K.S. (E)(U)\n"
"frameBufferEmulation\\copyToRDRAM=1\n"
"\n"
"[52150A67]\n"
"Good_Name=Bokujou Monogatari 2 (J)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[CASTLEVANIA2]\n"
"Good_Name=Castlevania - Legacy Of Darkness (E)(U)\n"
"frameBufferEmulation\\copyToRDRAM=1\n"
"\n"
"[DR.MARIO%2064]\n"
"Good_Name=Dr. Mario 64 (U)\n"
"frameBufferEmulation\\copyFromRDRAM=1\n"
"\n"
"[EXTREME_G]\n"
"Good_Name=Extreme-G (E)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[EXTREME-G]\n"
"Good_Name=Extreme-G (J)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[EXTREMEG]\n"
"Good_Name=Extreme-G (U)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[F1%20POLE%20POSITION%2064]\n"
"Good_Name=F-1 Pole Position 64 (E)(U)\n"
"frameBufferEmulation\\copyToRDRAM=1\n"
"\n"
"[HARVESTMOON64]\n"
"Good_Name=Harvest Moon 64 (U)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[5CFA0A2E]\n"
"Good_Name=Heiwa Pachinko World 64 (J)\n"
"frameBufferEmulation\\copyToRDRAM=1\n"
"\n"
"[HEXEN]\n"
"Good_Name=Hexen (E)(F)(G)(J)(U)\n"
"frameBufferEmulation\\copyToRDRAM=1\n"
"\n"
"[I%20S%20S%2064]\n"
"Good_Name=International Superstar Soccer 64 (E) (U)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[JET%20FORCE%20GEMINI]\n"
"Good_Name=Jet Force Gemini (E)(U)\n"
"; Show all crosshair reticules and miscellaneous graphics\n"
"frameBufferEmulation\\copyFromRDRAM=1\n"
"; Required for character select monitor and possibly other effects, but disabled due to #378\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[J%20F%20G%20DISPLAY]\n"
"; See Jet Force Gemini for notes\n"
"Good_Name=Jet Force Gemini Kiosk Demo (U)\n"
"frameBufferEmulation\\copyFromRDRAM=1\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[PERFECT%20STRIKER]\n"
"Good_Name=Jikkyou J.League Perfect Striker (J)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[301E07CC]\n"
"Good_Name=Mahjong Master (J)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[PENNY%20RACERS]\n"
"Good_Name=Penny Racers (E)(U)\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[POKEMON%20SNAP]\n"
"Good_Name=Pokemon Snap (U)\n"
"frameBufferEmulation\\copyAuxToRDRAM=1\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"frameBufferEmulation\\copyDepthToRDRAM=0\n"
"frameBufferEmulation\\copyFromRDRAM=1\n"
"\n"
"[POKEMON%20STADIUM%202]\n"
"Good_Name=Pokemon Stadium 2 (E)(F)(G)(I)(J)(S)(U)\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[POKEMON%20STADIUM%20G&S]\n"
"Good_Name=Pokemon Stadium Kin Gin (J)\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[RUSH%202049]\n"
"Good_Name=San Francisco Rush 2049 (E)(U)\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[SHADOWMAN]\n"
"Good_Name=Shadow Man (B)(E)(F)(G)(U)\n"
"frameBufferEmulation\\copyDepthToRDRAM=0\n"
"\n"
"[SPACE%20INVADERS]\n"
"Good_Name=Space Invaders (U)\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[STAR%20TWINS]\n"
"; See Jet Force Gemini for notes\n"
"Good_Name=Star Twins (J)\n"
"frameBufferEmulation\\copyFromRDRAM=1\n"
"frameBufferEmulation\\copyToRDRAM=0\n"
"\n"
"[TIGGER%27S%20HONEY%20HUNT]\n"
"Good_Name=Tigger's Honey Hunt (E)(U)\n"
"frameBufferEmulation\\N64DepthCompare=1\n"
"\n"
"[TONIC%20TROUBLE]\n"
"Good_Name=Tonic Trouble (E)(U)\n"
"frameBufferEmulation\\copyToRDRAM=1\n";
#endif
