#ifndef __CUSTOM_INI__
#define __CUSTOM_INI__

char customini[] = "[TWINE]\n"
"Good_Name=007 - The World Is Not Enough (E)(U)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[1080%20SNOWBOARDING]\n"
"Good_Name=1080 Snowboarding (E)(JU)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[6D120CBF]\n"
"Good_Name=64 De Hakken!! Tamagotchi - Minna De Tamagotchi World (J)\n"
"\n"
"[68DD0BB5]\n"
"Good_Name=64 Hanafuda - Tenshi No Yakusoku (J)\n"
"\n"
"[1F580575]\n"
"Good_Name=64 Oozumou 2 (J)\n"
"\n"
"[1333047D]\n"
"Good_Name=AI Shougi 3 (J)\n"
"\n"
"[30080737]\n"
"Good_Name=Air Boarder 64 (J)\n"
"\n"
"[44BB08DC]\n"
"Good_Name=Bakushou Jinsei 64 - Mezase! Resort Ou (J)\n"
"\n"
"[BANJO-KAZOOIE]\n"
"Good_Name=Banjo-Kazooie (E)(U) / Banjo To Kazooie No Daibouken (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[BANJO%20KAZOOIE%202]\n"
"Good_Name=Banjo to Kazooie no Daibouken 2 (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[BANJO%20TOOIE]\n"
"Good_Name=Banjo-Tooie (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[BEETLE%20ADVENTURE%20RAC]\n"
"Good_Name=Beetle Adventure Racing (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[BEETLE%20ADVENTURE%20JP]\n"
"Good_Name=Beetle Adventure Racing (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[BIOFREAKS]\n"
"Good_Name=Bio F.R.E.A.K.S. (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[52150A67]\n"
"Good_Name=Bokujou Monogatari 2 (J)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[476C09C1]\n"
"Good_Name=Bomberman Hero - Mirian Oujo Wo Sukue! (J)\n"
"\n"
"[13E50365]\n"
"Good_Name=Choro Q 64 2 - Hacha Mecha Grand Prix Race (J)\n"
"\n"
"[CASTLEVANIA]\n"
"Good_Name=Castlevania (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[CASTLEVANIA2]\n"
"Good_Name=Castlevania - Legacy Of Darkness (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[3D9F08DB]\n"
"Good_Name=Chou Kuukan Nighter Pro Yakyuu King 2 (J)\n"
"\n"
"[31DC0863]\n"
"Good_Name=Chou Snobow Kids (J)\n"
"\n"
"[CONKER%20BFD]\n"
"Good_Name=Conker's Bad Fur Day (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[362D06B6]\n"
"Good_Name=Densha de Go! 64 (J)\n"
"\n"
"[DONALD%20DUCK%20GOIN%27%20QU]\n"
"Good_Name=Donald Duck - Goin' Quackers (U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[DONALD%20DUCK%20QUACK%20AT]\n"
"Good_Name=Donald Duck - Quack Attack (E)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[DONKEY%20KONG%2064]\n"
"Good_Name=Donkey Kong 64 (E)(J)(U)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[D%20K%20DISPLAY]\n"
"Good_Name=Donkey Kong 64 Kiosk Demo (U)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[72390C86]\n"
"Good_Name=Doraemon - Nobita To 3tsu No Seireiseki (J)\n"
"\n"
"[6E3D0C76]\n"
"Good_Name=Doraemon 2 - Nobita To Hikari No Shinden (J)\n"
"\n"
"[84CE0BDF]\n"
"Good_Name=Doraemon 3 - Nobita No Machi SOS! (J)\n"
"\n"
"[DR.MARIO%2064]\n"
"Good_Name=Dr. Mario 64 (U)\n"
"frameBufferEmulation.copyFromRDRAM=1\n"
"\n"
"[67000C2B]\n"
"Good_Name=Eikou No Saint Andrews (J)\n"
"\n"
"[EXTREME_G]\n"
"Good_Name=Extreme-G (E)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[EXTREME-G]\n"
"Good_Name=Extreme-G (J)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[EXTREMEG]\n"
"Good_Name=Extreme-G (U)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[208E05CD]\n"
"Good_Name=Extreme-G XG2 (J)\n"
"\n"
"[F1%20POLE%20POSITION%2064]\n"
"Good_Name=F-1 Pole Position 64 (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[F-ZERO%20X]\n"
"Good_Name=F-Zero X (E)(J)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[18000458]\n"
"Good_Name=Famista 64 (J)\n"
"\n"
"[2997071D]\n"
"Good_Name=Fushigi No Dungeon - Fuurai No Shiren 2 - Oni Shuurai! Shiren Jou! (J)\n"
"\n"
"[3BE3091D]\n"
"Good_Name=Ganbare Goemon - Neo Momoyama Bakufu No Odori (J)\n"
"\n"
"[53900B10]\n"
"Good_Name=Goemon - Mononoke Sugoroku (J)\n"
"\n"
"[457A0908]\n"
"Good_Name=Hamster Monogatari 64 (J)\n"
"\n"
"[HARVESTMOON64]\n"
"Good_Name=Harvest Moon 64 (U)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[5CFA0A2E]\n"
"Good_Name=Heiwa Pachinko World 64 (J)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[HEXEN]\n"
"Good_Name=Hexen (E)(F)(G)(J)(U)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[30AB07E1]\n"
"Good_Name=Hiryuu No Ken Twin (J)\n"
"\n"
"[HSV%20ADVENTURE%20RACING]\n"
"Good_Name=HSV Adventure Racing (A)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[83CA0DCA]\n"
"Good_Name=Ide Yousuke No Mahjong Juku (J)\n"
"\n"
"[I%20S%20S%2064]\n"
"Good_Name=International Superstar Soccer 64 (E) (U)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[43CC08A2]\n"
"Good_Name=J.League Dynamite Soccer 64 (J)\n"
"\n"
"[7EA50BA0]\n"
"Good_Name=J.League Eleven Beat 1997 (J)\n"
"\n"
"[31E0076F]\n"
"Good_Name=Jangou Simulation Mahjong Dou 64 (J)\n"
"\n"
"[JET%20FORCE%20GEMINI]\n"
"Good_Name=Jet Force Gemini (E)(U)\n"
"; Show all crosshair reticules and miscellaneous graphics\n"
"frameBufferEmulation.copyFromRDRAM=1\n"
"; Required for character select monitor and possibly other effects, but disabled due to #378\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[J%20F%20G%20DISPLAY]\n"
"; See Jet Force Gemini for notes\n"
"Good_Name=Jet Force Gemini Kiosk Demo (U)\n"
"frameBufferEmulation.copyFromRDRAM=1\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[PERFECT%20STRIKER]\n"
"Good_Name=Jikkyou J.League Perfect Striker (J)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[713F0C09]\n"
"Good_Name=Kiratto Kaiketsu! 64 Tanteidan (J)\n"
"\n"
"[LEGORACERS]\n"
"Good_Name=Lego Racers (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[76910A78]\n"
"Good_Name=Mahjong Hourouki Classic (J)\n"
"\n"
"[301E07CC]\n"
"Good_Name=Mahjong Master (J)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[MARIOGOLF64]\n"
"Good_Name=Mario Golf (E)(J)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[MARIOKART64]\n"
"Good_Name=Mario Kart 64 (E)(J)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[2B6D07C8]\n"
"Good_Name=Mario No Photopi (J)\n"
"\n"
"[MARIO%20STORY]\n"
"Good_Name=Mario Story (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[MARIOTENNIS]\n"
"Good_Name=Mario Tennis (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[MARIOTENNIS64]\n"
"Good_Name=Mario Tennis 64 (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[MICKEY%20USA%20PAL]\n"
"Good_Name=Mickey's Speedway USA (E)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[MICKEY%20USA]\n"
"Good_Name=Mickey's Speedway USA (U) / Mickey No Racing Challenge USA (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[293D0695]\n"
"Good_Name=Morita Shougi 64 (J)\n"
"\n"
"[14B30473]\n"
"Good_Name=Nushi Duri 64 (J)\n"
"\n"
"[5E5A0B37]\n"
"Good_Name=Nushi Duri 64 - Shiokaze Ni Notte (J)\n"
"\n"
"[PAPER%20MARIO]\n"
"Good_Name=Paper Mario (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[PENNY%20RACERS]\n"
"Good_Name=Penny Racers (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[PERFECT%20DARK]\n"
"Good_Name=Perfect Dark (E)(J)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[POKEMON%20SNAP]\n"
"Good_Name=Pokemon Snap (U)\n"
"frameBufferEmulation.copyAuxToRDRAM=1\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"frameBufferEmulation.copyDepthToRDRAM=0\n"
"frameBufferEmulation.copyFromRDRAM=1\n"
"\n"
"[POKEMON%20STADIUM%202]\n"
"Good_Name=Pokemon Stadium 2 (E)(F)(G)(I)(J)(S)(U)\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[POKEMON%20STADIUM%20G&S]\n"
"Good_Name=Pokemon Stadium Kin Gin (J)\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[QUAKE%20II]\n"
"Good_Name=Quake II (U)\n"
"; set to 1 for correct HUD in pause menu\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[RAYMAN%202]\n"
"Good_Name=Rayman 2 - The Great Escape (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[437009B9]\n"
"Good_Name=Saikyou Habu Shougi (J)\n"
"\n"
"[RUSH%202049]\n"
"Good_Name=San Francisco Rush 2049 (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[1C500641]\n"
"Good_Name=Snobow Kids (J)\n"
"\n"
"[SPACE%20INVADERS]\n"
"Good_Name=Space Invaders (U)\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[75DA0AC4]\n"
"Good_Name=Star Craft 64 (J)\n"
"\n"
"[STAR%20TWINS]\n"
"; See Jet Force Gemini for notes\n"
"Good_Name=Star Twins (J)\n"
"frameBufferEmulation.copyFromRDRAM=1\n"
"frameBufferEmulation.copyToRDRAM=0\n"
"\n"
"[STAR%20WARS%20EP1%20RACER]\n"
"Good_Name=Star Wars Episode I - Racer (E)(U)(J)\n"
"\n"
"[67ED0B45]\n"
"Good_Name=Super Robot Taisen 64 (J)\n"
"\n"
"[622D0C12]\n"
"Good_Name=Susume! Taisen Puzzle Dama - Toukon! Marutama Chou (J)\n"
"\n"
"[ZELDA%20MAJORA%27S%20MASK]\n"
"Good_Name=The Legend Of Zelda - Majora's Mask (E)(U) / Zelda No Densetsu - Mujura No Karmen (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[MAJORA%27S%20MASK]\n"
"Good_Name=The Legend Of Zelda - Majora's Mask Demo (U)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[THE%20LEGEND%20OF%20ZELDA]\n"
"Good_Name=The Legend Of Zelda - Ocarina Of Time (E)(U) / Zelda No Densetsu - Toki No Ocarina (J)\n"
"\n"
"[ZELDA%20MASTER%20QUEST]\n"
"Good_Name=The Legend Of Zelda - Ocarina Of Time - Master Quest\n"
"\n"
"[TIGGER%27S%20HONEY%20HUNT]\n"
"Good_Name=Tigger's Honey Hunt (E)(U)\n"
"frameBufferEmulation.N64DepthCompare=1\n"
"\n"
"[TONIC%20TROUBLE]\n"
"Good_Name=Tonic Trouble (E)(U)\n"
"frameBufferEmulation.copyToRDRAM=1\n"
"\n"
"[48460A35]\n"
"Good_Name=Ucchan Nanchan No Hono No Challenger - Denryuu Ira Ira Bou (J)\n"
"\n"
"[VIGILANTE%208]\n"
"Good_Name=Vigilante 8 (E)(F)(G)(U)\n"
"\n"
"[4C2E093B]\n"
"Good_Name=Virtual Pro Wrestling 2 - Oudou Keishou (J)\n"
"\n"
"[8B6F0CBE]\n"
"Good_Name=Virtual Pro Wrestling 64 (J)\n"
"\n"
"[34060655]\n"
"Good_Name=WWF Wrestlemania 2000 (J)\n"
"\n"
"[THE%20MASK%20OF%20MUJURA]\n"
"Good_Name=Zelda No Densetsu - Mujura No Karmen (J)\n"
"frameBufferEmulation.copyToRDRAM=2\n"
"\n"
"[7BC50D43]\n"
"Good_Name=Zool - Majuu Tsukai Densetsu (J)\n"
"\n";
#endif
